name: build
on:
  - pull_request
  - push
jobs:
  build:
    strategy:
      matrix:
        java:
          - 16
        os:
          - macos-latest
          - windows-latest
          - linux-latest
    runs-on: '${{ matrix.os }}'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '${{ matrix.java }}'
          distribution: adopt
      - run: chmod +x ./gradlew
      - run: ./gradlew build
      - name: Create Dev Build release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: latest
          prerelease: true
          title: Dev Build
          files: |
            ./build/libs/*.jar
